<?php

namespace Lv\SaladeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComposanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposanteRepository extends EntityRepository
{
}
