<?php

namespace Lv\SaladeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousFamilleRepository extends EntityRepository
{
}
