parameters:
#    star_user.example.class: Star\UserBundle\Example

services:
#    star_user.example:
#        class: %star_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lv_user.registration.form.type:
        class: Lv\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: lv_user_registration }
